fortuneproj/fortuneproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('place/', include('place.urls')),
    path('fortune/', include('fortune.urls')),
    path('', include('register.urls')),
]

fortuneproj/place/urls.py
from django.urls import path
from .views import detail_place

urlpatterns = [
    path('detail/<int:pk>/', detail_place, name='detail_place'),
]

fortuneproj/register/urls.py
from django.urls import path

from . import views

app_name = 'register'

urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
]

fortuneproj/place/models.py
from django.db import models


class Place(models.Model):
    name = models.CharField(max_length=255)
    text = models.TextField()
    lng= models.FloatField()
    lat = models.FloatField()
    attribute = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class PlaceComment(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    user_name = models.CharField('ユーザ名', max_length=50)
    text = models.TextField('コメント')

    def __str__(self):
        return f"{self.place}に対する{self.user_name}のコメント"

fortuneproj/place/forms.py
from django import forms

from .models import Place, PlaceComment


# inline_formsetでPlaceとPlaceCommentを同時に取得
class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = '__all__'


class PlaceCommentForm(forms.ModelForm):
    class Meta:
        model = PlaceComment
        fields = ('text', 'user_name')

fortuneproj/place/views.py
from os import getenv

from django.db import transaction
from django.shortcuts import get_object_or_404, render

from .forms import PlaceCommentForm
from .models import Place, PlaceComment

api_key = getenv("MAP_API_KEY")


@transaction.atomic
def detail_place(request, pk):
    place = get_object_or_404(Place, pk=pk)
    comment = PlaceComment.objects.filter(place=place)
    comment_form = PlaceCommentForm(request.POST or None)
    template = 'place/detail_place.html'

    if request.method == "POST" and comment_form.is_valid():
        new_comment = comment_form.save(commit=False)
        new_comment.place = place
        new_comment.save()
        comment_form = PlaceCommentForm()

    contexts = {
        'api_key': api_key,
        'place': place,
        'comment': comment,
        'form': comment_form,
    }

    return render(request, template, contexts)

fortuneproj/place/templates/place/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'register/css/material-dashboard.min.css' %}">
    <title>サンプルアプリ</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'register:top' %}">サンプルアプリ</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_detail' user.pk %}">アカウント情報</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:user_update' user.pk %}">アカウント情報</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:logout' %}">ログアウト</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:password_change' %}">パスワードの変更</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'register:email_change' %}">メールアドレスの変更</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-item nav-link" href="{% url 'register:login' %}">
            ログインはこちら
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-3">
      {% block content %}{% endblock %}
  </div>
  <script src="{% static 'register/js/material-dashboard.min.js' %}"></script>
</body>
</html>

fortuneproj/place/templates/place/detail_place.html
{% extends 'place/base.html' %}
{% block content %}
<div id="map"></div>
<div class="card col-md-12 m-5">
  <div class="card-header card-header-primary">
    場所
  </div>
  <div class="card-body">
    <h4 class="card-title">{{ place.name }}</h4>
    <p>{{ place.text }}</p>
  </div>
</div>
<div class="card col-md-12 m-5">
  <div class="card-header card-header-primary">
    コメント
  </div>
  {% for comment in place.placecomment_set.all %}
  <div class="card-body">
    <p>{{ comment.user_name }}</p>
    <p>{{ comment.text }}</p>
  </div>
  {% endfor %}
</div>
<div class="card col-md-12 m-5">
  <div class="card-header card-header-primary">
    コメントする
  </div>
  <form method="post">
    <div class="card-body">
      {{ form.as_p }}
    </div>
    {% csrf_token %}
    <button type="submit">投稿する</button>
  </form>
</div>
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script
  src="https://maps.googleapis.com/maps/api/js?key={{api_key}}&callback=initMap&libraries=&v=weekly"
  defer
></script>
<style type="text/css">
  /* Always set the map height explicitly to define the size of the div
    * element that contains the map. */
  #map {
    height: 100%;
  }

  /* Optional: Makes the sample page fill the window. */
  html,
  body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
  #map {
    position: relative;
    padding-bottom: 75%; // これが縦横比
    height: 0;
    overflow: hidden;
  }
  #map iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100% !important;
    height: 100% !important;
  }
</style>
<script>
  "use strict";
  // This example displays a map with the language set to Arabic and the
  // regions set to Egypt. These settings are specified in the HTML script
  // element when loading the Google Maps JavaScript API.
  // Setting the language shows the map in the language of your choice.
  // Setting the region biases the geocoding results to that region.
  // In addition, the page's html element sets the text direction to
  // right-to-left.
  function initMap() {
    const place = {
      lat: {{ place.lat }},
      lng: {{ place.lng}}
    };
    const map = new google.maps.Map(document.getElementById("map"), {
      scaleControl: true,
      center: place,
      zoom: 10
    });
    const infowindow = new google.maps.InfoWindow();
    infowindow.setContent("{{place.name}}");
    const marker = new google.maps.Marker({
      map,
      position: place
    });
    marker.addListener("click", () => {
      infowindow.open(map, marker);
    });
  }
</script>
{% endblock %}

fortuneproj/place/templates/place/fortune_list.html
{% extends 'place/base.html' %}
{% block content %}
あなたのユーザタイプは {{ user_type }} です。
本日の吉方位は {{ fortune_direction }} です。

吉方位にあるパワースポットリストです。
<ul>
{% for spot in spot_list%}
<li>{{ spot }}</li>
{% endfor %}
</ul>
{% endblock %}